#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-session
Version  : 3.28.1
Release  : 18
URL      : https://download.gnome.org/sources/gnome-session/3.28/gnome-session-3.28.1.tar.xz
Source0  : https://download.gnome.org/sources/gnome-session/3.28/gnome-session-3.28.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gnome-session-bin
Requires: gnome-session-data
Requires: gnome-session-doc
Requires: gnome-session-locales
BuildRequires : docbook-xml
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(xtrans)
BuildRequires : python3
BuildRequires : systemd-dev
BuildRequires : upower-dev
BuildRequires : xmlto

%description
gnome-session
=============
gnome-session contains the GNOME session manager, as well as a
configuration program to choose applications starting on login.

%package bin
Summary: bin components for the gnome-session package.
Group: Binaries
Requires: gnome-session-data

%description bin
bin components for the gnome-session package.


%package data
Summary: data components for the gnome-session package.
Group: Data

%description data
data components for the gnome-session package.


%package doc
Summary: doc components for the gnome-session package.
Group: Documentation

%description doc
doc components for the gnome-session package.


%package locales
Summary: locales components for the gnome-session package.
Group: Default

%description locales
locales components for the gnome-session package.


%prep
%setup -q -n gnome-session-3.28.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523372605
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain  builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-session-3.0

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-session
/usr/bin/gnome-session-custom-session
/usr/bin/gnome-session-inhibit
/usr/bin/gnome-session-quit
/usr/libexec/gnome-session-binary
/usr/libexec/gnome-session-check-accelerated
/usr/libexec/gnome-session-check-accelerated-gl-helper
/usr/libexec/gnome-session-check-accelerated-gles-helper
/usr/libexec/gnome-session-failed

%files data
%defattr(-,root,root,-)
/usr/share/GConf/gsettings/gnome-session.convert
/usr/share/glib-2.0/schemas/org.gnome.SessionManager.gschema.xml
/usr/share/gnome-session/hardware-compatibility
/usr/share/gnome-session/sessions/gnome-dummy.session
/usr/share/gnome-session/sessions/gnome.session
/usr/share/wayland-sessions/gnome.desktop
/usr/share/xsessions/gnome-xorg.desktop
/usr/share/xsessions/gnome.desktop

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/gnome\-session/*
%doc /usr/share/man/man1/*

%files locales -f gnome-session-3.0.lang
%defattr(-,root,root,-)

